// src/routes/projects.svelte
<script>
	import Project from '$lib/Project.svelte'
</script>

<Project
	title="Tradebreaker"
	img="/tradebreaker.png"
	web="https://tradebreaker.io"
	iOS="https://apps.apple.com/us/app/tradebreaker/id1471192218"
	android="https://play.google.com/store/apps/details?id=xyz.appmaker.szwfyz&hl=en_CA"
>
	Aggregates NHL news on Twitter and notifies you when they are added. It uses Natural Language
	Processing to parse the tweets from select NHL insiders and detect whether or not it's actual
	news. While it's not perfect, it is still a reliable way to be notified within seconds of news
	breaking on Twitter.
</Project>

// pages/projects.tsx
import React from 'react'
import { motion } from 'framer-motion'
import Head from 'next/head'
import Header from 'components/Header'
import Link from 'next/link'
import { GetStaticProps } from 'next'

const items = [
  {
    title: `Tradebreaker`,
    description: `Notifies you when NHL trades are reported on Twitter`,
    web: `https://tradebreaker.io`,
    iOS: `https://apps.apple.com/us/app/tradebreaker/id1471192218`,
    android: `https://play.google.com/store/apps/details?id=xyz.appmaker.szwfyz&hl=en_CA`,
  },
  {
    title: `svelte-phaser`,
    description: `Create Phaser games with Svelte`,
    source: `https://github.com/mattjennings/svelte-phaser`,
  },
  {
    title: `react-phaser-fiber`,
    description: `Create Phaser games with React`,
    source: `https://github.com/mattjennings/react-phaser-fiber`,
  },
  {
    title: `Hockey Stats`,
    description: `NHL stats website built with Gatsby`,
    web: `https://hockey-stats.netlify.com/`,
    source: `https://github.com/mattjennings/gatsby-hockey-stats`,
  },
  {
    title: `Friedman Decryptor`,
    description: `Decrypts Elliotte Friedman's acronyms that nobody understands`,
    web: `https://friedgism.mattjennings.io/`,
    source: `https://github.com/mattjennings/friedman-decryptor`,
  },
]

export default function Projects() {
  return (
    <>
      <Header.Content>Projects</Header.Content>
      <div className="pt-6">
        <Link href="/">
          <a>home</a>
        </Link>
      </div>
    </>
  )
}
